import { Array, Option, Schema as S } from "effect";

export const ExampleSlug = S.Literals([
  "counter",
  "counters",
  "todo",
  "stopwatch",
  "crash-view",
  "slow-warnings",
  "form",
  "job-application",
  "weather",
  "api-cache",
  "charting",
  "routing",
  "route-transitions",
  "interrupting-commands",
  "view-transitions",
  "query-sync",
  "snake",
  "auth",
  "shopping-cart",
  "state-machine",
  "pixel-art",
  "websocket-chat",
  "managed-resource-layer",
  "kanban",
  "map",
  "canvas-art",
  "generative-art",
  "web-components",
  "embedding",
  "ui-showcase",
  "personal-blog",
]);
export type ExampleSlug = typeof ExampleSlug.Type;

export const Difficulty = S.Literals(["Beginner", "Intermediate", "Advanced"]);
export type Difficulty = typeof Difficulty.Type;

export type Example = Readonly<{
  slug: ExampleSlug;
  title: string;
  description: string;
  difficulty: Difficulty;
  tags: ReadonlyArray<string>;
  status: "Ready" | "Planned";
}>;

export const examples: ReadonlyArray<Example> = [
  {
    slug: "counter",
    title: "Counter",
    description:
      "Increment, decrement, and reset a number with one Model and pure update function.",
    difficulty: "Beginner",
    tags: ["State"],
    status: "Ready",
  },
  {
    slug: "counters",
    title: "Counters",
    description: "A dynamic list of independent Counter Submodels with wrapper Message routing.",
    difficulty: "Beginner",
    tags: ["Submodels"],
    status: "Planned",
  },
  {
    slug: "todo",
    title: "Todo",
    description: "A todo list with local storage persistence and complete CRUD behavior.",
    difficulty: "Beginner",
    tags: ["Storage"],
    status: "Planned",
  },
  {
    slug: "stopwatch",
    title: "Stopwatch",
    description: "A stopwatch demonstrating time-based Subscriptions.",
    difficulty: "Beginner",
    tags: ["Subscriptions"],
    status: "Planned",
  },
  {
    slug: "crash-view",
    title: "Crash View",
    description: "Custom crash fallback UI and reporting.",
    difficulty: "Beginner",
    tags: ["Fallback UI"],
    status: "Planned",
  },
  {
    slug: "slow-warnings",
    title: "Slow Warnings",
    description: "A lab for triggering and inspecting runtime performance warnings.",
    difficulty: "Intermediate",
    tags: ["Performance", "Diagnostics"],
    status: "Planned",
  },
  {
    slug: "form",
    title: "Form",
    description: "Field validation, error states, and asynchronous submission.",
    difficulty: "Intermediate",
    tags: ["Validation"],
    status: "Planned",
  },
  {
    slug: "job-application",
    title: "Job Application",
    description: "A multi-step form with cross-field validation, files, and per-step errors.",
    difficulty: "Advanced",
    tags: ["Validation", "Multi-step", "UI Components"],
    status: "Planned",
  },
  {
    slug: "weather",
    title: "Weather",
    description: "HTTP requests with explicit loading and error states.",
    difficulty: "Intermediate",
    tags: ["HTTP"],
    status: "Planned",
  },
  {
    slug: "api-cache",
    title: "API Cache",
    description: "Stale-while-revalidate, request deduplication, invalidation, and refetching.",
    difficulty: "Intermediate",
    tags: ["Caching", "Subscriptions"],
    status: "Planned",
  },
  {
    slug: "charting",
    title: "Charting",
    description: "Effectful telemetry loading with an ECharts Mount adapter.",
    difficulty: "Advanced",
    tags: ["Charts", "HTTP", "Mount"],
    status: "Planned",
  },
  {
    slug: "routing",
    title: "Routing Lab",
    description: "Every public Foldkit route, navigation, and transition capability in one lab.",
    difficulty: "Intermediate",
    tags: ["Routing"],
    status: "Ready",
  },
  {
    slug: "route-transitions",
    title: "Route Transitions",
    description: "Entering, stayed, exited, and cold-load route lifecycle policies.",
    difficulty: "Intermediate",
    tags: ["Routing", "Transitions", "Commands"],
    status: "Planned",
  },
  {
    slug: "interrupting-commands",
    title: "Interrupting Commands",
    description: "Keyed interruption for concurrent simulated uploads.",
    difficulty: "Intermediate",
    tags: ["Commands", "Concurrency"],
    status: "Planned",
  },
  {
    slug: "view-transitions",
    title: "View Transitions",
    description: "Direction-aware route animation and shared-element transitions.",
    difficulty: "Intermediate",
    tags: ["Routing", "Animation"],
    status: "Planned",
  },
  {
    slug: "query-sync",
    title: "Query Sync",
    description: "Schema-decoded controls synchronized bidirectionally with URL query parameters.",
    difficulty: "Intermediate",
    tags: ["Routing", "Query Params"],
    status: "Planned",
  },
  {
    slug: "snake",
    title: "Snake",
    description: "Keyboard input, a game loop Subscription, and collision detection.",
    difficulty: "Advanced",
    tags: ["Game"],
    status: "Planned",
  },
  {
    slug: "auth",
    title: "Auth",
    description: "Protected routes with Submodels, OutMessage, and session management.",
    difficulty: "Advanced",
    tags: ["Auth", "Routing", "Submodels"],
    status: "Planned",
  },
  {
    slug: "shopping-cart",
    title: "Shopping Cart",
    description: "Product browsing, cart state, and checkout navigation.",
    difficulty: "Advanced",
    tags: ["Routing"],
    status: "Planned",
  },
  {
    slug: "state-machine",
    title: "State Machine",
    description: "A guarded checkout workflow using the experimental machine module.",
    difficulty: "Advanced",
    tags: ["State Machines", "Commands"],
    status: "Planned",
  },
  {
    slug: "pixel-art",
    title: "Pixel Art",
    description: "An editor with undo, redo, persistence, export, and optimized rendering.",
    difficulty: "Advanced",
    tags: ["Undo/Redo", "UI Components", "Storage"],
    status: "Planned",
  },
  {
    slug: "websocket-chat",
    title: "WebSocket Chat",
    description: "Managed WebSocket lifecycle, reconnection, and message streaming.",
    difficulty: "Advanced",
    tags: ["Managed Resources", "WebSocket"],
    status: "Planned",
  },
  {
    slug: "managed-resource-layer",
    title: "Managed Resource Layer",
    description: "A Layer-backed ManagedResource with Commands and finalizers.",
    difficulty: "Advanced",
    tags: ["Managed Resources", "Effect Layer"],
    status: "Planned",
  },
  {
    slug: "kanban",
    title: "Kanban",
    description: "Accessible cross-column drag and drop with persistent ordering.",
    difficulty: "Advanced",
    tags: ["Drag & Drop", "Submodels", "Storage"],
    status: "Planned",
  },
  {
    slug: "map",
    title: "Map",
    description: "MapLibre integration through Mount and event Subscriptions.",
    difficulty: "Advanced",
    tags: ["Mount", "Subscriptions"],
    status: "Planned",
  },
  {
    slug: "canvas-art",
    title: "Canvas Art",
    description: "Declarative canvas rendering with pointer and animation-frame events.",
    difficulty: "Intermediate",
    tags: ["Canvas", "Animation"],
    status: "Planned",
  },
  {
    slug: "generative-art",
    title: "Generative Art",
    description: "A reactive flow field with particles, Effect Random, and Canvas.",
    difficulty: "Advanced",
    tags: ["Canvas", "Animation", "Generative"],
    status: "Planned",
  },
  {
    slug: "web-components",
    title: "Web Components",
    description: "Third-party custom elements connected through a single Foldkit Model.",
    difficulty: "Advanced",
    tags: ["Web Components", "CustomElement"],
    status: "Planned",
  },
  {
    slug: "embedding",
    title: "Embedding",
    description: "A Foldkit widget embedded through Schema-typed Ports.",
    difficulty: "Advanced",
    tags: ["Embedding", "Ports"],
    status: "Planned",
  },
  {
    slug: "ui-showcase",
    title: "UI Showcase",
    description: "Button, Dialog, and Combobox from the Foldkit-native @pkg/ui package.",
    difficulty: "Advanced",
    tags: ["UI Components", "Routing"],
    status: "Ready",
  },
  {
    slug: "personal-blog",
    title: "Personal Blog",
    description: "Typed Markdown documents with live Submodel islands.",
    difficulty: "Advanced",
    tags: ["Markdown", "Islands", "Routing"],
    status: "Planned",
  },
];

export const findExample = (slug: string): Option.Option<Example> =>
  Array.findFirst(examples, (example) => example.slug === slug);

export const exampleSourceUrl = (slug: string): string =>
  `https://github.com/foldkit/foldkit/tree/main/examples/${slug}`;
