import { Schema as S } from "effect";

export const Catalog = S.Literals(["parts", "standalone"]);
export type Catalog = typeof Catalog.Type;

export const BehaviorClass = S.Literals(["A", "B", "C"]);
export type BehaviorClass = typeof BehaviorClass.Type;

export const Status = S.Literals(["planned", "contract-reviewed", "implemented", "verified"]);
export type Status = typeof Status.Type;

export const Phase = S.Int.check(S.isBetween({ minimum: 1, maximum: 7 }));
export type Phase = typeof Phase.Type;

export const ComponentMetadata = S.Struct({
  name: S.String,
  title: S.String,
  slug: S.String,
  catalog: Catalog,
  phase: Phase,
  behaviorClass: BehaviorClass,
  behaviorAuthority: S.String,
  status: Status,
  family: S.String,
  dependencies: S.Array(S.String),
  anatomy: S.Array(S.String),
  publicParts: S.Array(S.String),
  states: S.Array(S.String),
  slots: S.Array(S.String),
  heroUi: S.Struct({ version: S.String, module: S.String }),
  foldkit: S.Struct({ primitive: S.String }),
  examples: S.Array(S.String),
  differences: S.Array(S.String),
});
export type ComponentMetadata = typeof ComponentMetadata.Type;

export const typographyMetadata = ComponentMetadata.make({
  name: "Typography",
  title: "排版",
  slug: "typography",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生文本语义",
  status: "verified",
  family: "foundations",
  dependencies: ["@heroui/styles/components/typography", "foldkit/html"],
  anatomy: ["语义文本元素", "typography slot"],
  publicParts: ["view", "proseView"],
  states: ["type", "align", "color", "weight", "truncate"],
  slots: ["content", "prose content"],
  heroUi: { version: "3.2.4", module: "typography" },
  foldkit: { primitive: "原生 h1-h6、p、code、div" },
  examples: ["default", "semantic-levels", "variants", "custom-content", "long-text"],
  differences: ["不引入 React Aria Text；元素语义由 Foldkit HtmlBuilder 直接生成。"],
});

export const surfaceMetadata = ComponentMetadata.make({
  name: "Surface",
  title: "表面",
  slug: "surface",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生容器语义",
  status: "verified",
  family: "foundations",
  dependencies: ["@heroui/styles/components/surface", "foldkit/html"],
  anatomy: ["内容容器", "surface slot"],
  publicParts: ["view"],
  states: ["default", "secondary", "tertiary", "transparent"],
  slots: ["content"],
  heroUi: { version: "3.2.4", module: "surface" },
  foldkit: { primitive: "原生容器与调用方 attributes" },
  examples: ["default", "variants", "custom-content", "narrow-content"],
  differences: ["不移植 React Context；Surface 不持有或传播行为状态。"],
});

export const separatorMetadata = ComponentMetadata.make({
  name: "Separator",
  title: "分隔线",
  slug: "separator",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生 separator 语义",
  status: "verified",
  family: "foundations",
  dependencies: ["@heroui/styles/components/separator", "foldkit/html"],
  anatomy: ["separator root"],
  publicParts: ["view"],
  states: ["horizontal", "vertical", "default", "secondary", "tertiary"],
  slots: ["separator"],
  heroUi: { version: "3.2.4", module: "separator" },
  foldkit: { primitive: "原生 role=separator 与 aria-orientation" },
  examples: ["default", "color-variants", "vertical"],
  differences: ["不引入 React Aria Separator；role 与 aria-orientation 由原生属性表达。"],
});

export const labelMetadata = ComponentMetadata.make({
  name: "Label",
  title: "字段标签",
  slug: "label",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生 label 关系",
  status: "verified",
  family: "form-control",
  dependencies: ["@heroui/styles/components/label", "foldkit/html"],
  anatomy: ["原生 label 元素", "label slot"],
  publicParts: ["view"],
  states: ["default", "required", "disabled", "invalid"],
  slots: ["content"],
  heroUi: { version: "3.2.4", module: "label" },
  foldkit: { primitive: "原生 label 与 for/id relationship" },
  examples: ["default", "required", "invalid", "disabled", "long-content"],
  differences: ["不引入 React Aria Label；for/id 与字段状态继续由调用方提供。"],
});

export const descriptionMetadata = ComponentMetadata.make({
  name: "Description",
  title: "字段说明",
  slug: "description",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "稳定 Description Channel",
  status: "verified",
  family: "form-control",
  dependencies: ["@heroui/styles/components/description", "foldkit/html"],
  anatomy: ["稳定 description 容器", "description slot"],
  publicParts: ["view"],
  states: ["helper", "validating", "errors", "empty", "long-content"],
  slots: ["content"],
  heroUi: { version: "3.2.4", module: "description" },
  foldkit: { primitive: "原生 id 与 aria-describedby relationship" },
  examples: ["controlled-content", "default", "empty", "long-content"],
  differences: ["不依赖 React Aria Text slot；容器是否挂载及其 id 由 Field Anatomy 决定。"],
});

export const headerMetadata = ComponentMetadata.make({
  name: "Header",
  title: "区块标题",
  slug: "header",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生 header 与调用方内容语义",
  status: "verified",
  family: "foundations",
  dependencies: ["@heroui/styles/components/header", "foldkit/html"],
  anatomy: ["原生 header 容器", "调用方标题内容", "header slot"],
  publicParts: ["view"],
  states: ["default", "long-content"],
  slots: ["content"],
  heroUi: { version: "3.2.4", module: "header" },
  foldkit: { primitive: "原生 header 与调用方 heading" },
  examples: ["default", "custom-heading", "long-content"],
  differences: ["不引入 React Aria Header；标题层级与集合关系由调用方内容表达。"],
});

export const errorMessageMetadata = ComponentMetadata.make({
  name: "ErrorMessage",
  title: "错误消息",
  slug: "error-message",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "外部校验事实与原生描述关系",
  status: "verified",
  family: "form-control",
  dependencies: ["@heroui/styles/components/error-message", "foldkit/html"],
  anatomy: ["错误消息容器", "error-message slot"],
  publicParts: ["view"],
  states: ["external-error", "long-content"],
  slots: ["content"],
  heroUi: { version: "3.2.4", module: "error-message" },
  foldkit: { primitive: "调用方校验状态与原生 aria-describedby" },
  examples: ["external-error", "long-content"],
  differences: ["不依赖 React Aria Text slot；组件不决定何时产生、显示或清除错误。"],
});

export const fieldErrorMetadata = ComponentMetadata.make({
  name: "FieldError",
  title: "字段错误",
  slug: "field-error",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "外层 Form Model 与稳定 Description Channel",
  status: "verified",
  family: "form-control",
  dependencies: ["@heroui/styles/components/field-error", "foldkit/html"],
  anatomy: ["稳定字段错误容器", "field-error slot"],
  publicParts: ["view"],
  states: ["external-visible", "external-hidden", "empty", "multiple-errors"],
  slots: ["content"],
  heroUi: { version: "3.2.4", module: "field-error" },
  foldkit: { primitive: "Form Model errors 与原生 aria-describedby" },
  examples: ["external-visible", "external-hidden", "empty", "multiple-errors"],
  differences: ["不引入 React Aria FieldError 的校验读取；外层 Field 决定内容并保持稳定 id。"],
});

export const kbdMetadata = ComponentMetadata.make({
  name: "Kbd",
  title: "键盘提示",
  slug: "kbd",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生 kbd 与 abbr 语义",
  status: "verified",
  family: "foundations",
  dependencies: ["@heroui/styles/components/kbd", "foldkit/html"],
  anatomy: ["原生 kbd root", "abbr key", "content slot"],
  publicParts: ["view", "abbrView", "contentView"],
  states: ["default", "light"],
  slots: ["key abbreviation", "content"],
  heroUi: { version: "3.2.4", module: "kbd" },
  foldkit: { primitive: "原生 kbd、abbr、title" },
  examples: ["default", "light", "combination", "long-content"],
  differences: ["不引入 React Context；abbrView 与 contentView 显式组成同一 kbd 内容。"],
});

export const badgeMetadata = ComponentMetadata.make({
  name: "Badge",
  title: "徽标",
  slug: "badge",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生容器与调用方状态语义",
  status: "verified",
  family: "data-display",
  dependencies: ["@heroui/styles/components/badge", "foldkit/html"],
  anatomy: ["badge anchor", "badge root", "badge label"],
  publicParts: ["view", "labelView", "anchorView"],
  states: ["color", "variant", "size", "placement"],
  slots: ["anchor", "badge", "label"],
  heroUi: { version: "3.2.4", module: "badge" },
  foldkit: { primitive: "原生 span 与调用方 attributes" },
  examples: ["status", "colors", "variants", "sizes", "placements", "long-content"],
  differences: ["不移植 React Context；status、live region 与更新时机由调用方提供。"],
});

export const chipMetadata = ComponentMetadata.make({
  name: "Chip",
  title: "标签块",
  slug: "chip",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "调用方内容与真实交互控件",
  status: "verified",
  family: "data-display",
  dependencies: ["@heroui/styles/components/chip", "foldkit/html"],
  anatomy: ["chip root", "chip label", "调用方交互内容"],
  publicParts: ["view", "labelView"],
  states: ["color", "variant", "size", "custom-radius"],
  slots: ["chip", "label", "caller content"],
  heroUi: { version: "3.2.4", module: "chip" },
  foldkit: { primitive: "原生 span 与调用方真实控件" },
  examples: ["default", "colors", "variants", "sizes", "caller-action", "long-content"],
  differences: ["不移植 React Context；删除等交互动作必须由调用方真实控件派发 Message。"],
});

export const cardMetadata = ComponentMetadata.make({
  name: "Card",
  title: "卡片",
  slug: "card",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生容器与调用方内容语义",
  status: "verified",
  family: "layout",
  dependencies: ["@heroui/styles/components/card", "effect", "foldkit/html"],
  anatomy: ["card root", "header", "title", "description", "content", "footer"],
  publicParts: ["view", "headerView", "titleView", "descriptionView", "contentView", "footerView"],
  states: ["default", "secondary", "tertiary", "transparent", "custom-radius"],
  slots: ["header", "title", "description", "content", "footer"],
  heroUi: { version: "3.2.4", module: "card" },
  foldkit: { primitive: "原生 div、heading、p 与调用方 attributes" },
  examples: ["default", "variants", "semantic-title", "nested-content", "long-content"],
  differences: ["不移植 React Context 或 SurfaceContext；内容语义与 landmark 由调用方提供。"],
});

export const skeletonMetadata = ComponentMetadata.make({
  name: "Skeleton",
  title: "加载占位",
  slug: "skeleton",
  catalog: "parts",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "外层 Model 的 loading 事实",
  status: "verified",
  family: "feedback",
  dependencies: ["@heroui/styles/components/skeleton", "foldkit/html"],
  anatomy: ["skeleton root", "optional nested skeleton content"],
  publicParts: ["view"],
  states: ["shimmer", "pulse", "none", "external-loading", "custom-shape"],
  slots: ["root", "optional content"],
  heroUi: { version: "3.2.4", module: "skeleton" },
  foldkit: { primitive: "外层 Model 分支、原生 aria-busy 与 div" },
  examples: ["external-loading", "animation-types", "shapes", "custom-radius"],
  differences: ["不读取 CSS variable 来创建本地状态；loading 与 aria-busy 始终由外层调用方提供。"],
});

export const emptyStateMetadata = ComponentMetadata.make({
  name: "EmptyState",
  title: "空状态",
  slug: "empty-state",
  catalog: "standalone",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "外层 empty 事实与调用方真实操作控件",
  status: "verified",
  family: "feedback",
  dependencies: ["@heroui/styles/components/empty-state", "foldkit/html"],
  anatomy: ["empty-state root", "caller title", "caller description", "caller actions"],
  publicParts: ["view"],
  states: ["external-empty", "primary-action", "secondary-action", "no-action"],
  slots: ["root", "caller content"],
  heroUi: { version: "3.2.4", module: "empty-state" },
  foldkit: { primitive: "外层 Model、原生 heading、button、link 与 attributes" },
  examples: ["default", "primary-secondary-actions", "no-action", "long-content", "rtl"],
  differences: ["不保存 empty 事实；标题、描述与操作均是调用方拥有的真实内容。"],
});

export const alertMetadata = ComponentMetadata.make({
  name: "Alert",
  title: "提示",
  slug: "alert",
  catalog: "standalone",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生 alert/status live-region 语义",
  status: "verified",
  family: "feedback",
  dependencies: ["@heroui/styles/components/alert", "effect", "foldkit/html"],
  anatomy: ["alert root", "indicator", "content", "title", "description"],
  publicParts: ["view", "indicatorView", "contentView", "titleView", "descriptionView"],
  states: ["default", "accent", "success", "warning", "danger", "alert", "status"],
  slots: ["indicator", "content", "title", "description"],
  heroUi: { version: "3.2.4", module: "alert" },
  foldkit: { primitive: "原生 div、role=alert/status 与调用方 attributes" },
  examples: ["urgent-alert", "polite-status", "statuses", "custom-content", "rtl"],
  differences: ["不移植 React Context 或默认图标；调用方显式提供 indicator 与语义用途。"],
});

export const spinnerMetadata = ComponentMetadata.make({
  name: "Spinner",
  title: "加载指示器",
  slug: "spinner",
  catalog: "standalone",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生 status 与调用方 loading 事实",
  status: "verified",
  family: "feedback",
  dependencies: ["@heroui/styles/components/spinner", "foldkit/html"],
  anatomy: ["status root", "decorative spinner icon"],
  publicParts: ["view"],
  states: ["indeterminate", "accent", "current", "success", "warning", "danger", "size"],
  slots: ["spinner", "spinner-icon"],
  heroUi: { version: "3.2.4", module: "spinner" },
  foldkit: { primitive: "原生 role=status、accessible name 与调用方 attributes" },
  examples: ["default", "colors", "sizes", "custom-label", "reduced-motion"],
  differences: [
    "不保存 loading 事实；accessibleLabel 由调用方按任务上下文显式提供。",
    "Foldkit 没有 React useId；调用方提供 gradientId，确保页面内每个官方双渐变 icon 的引用唯一。",
  ],
});

export const progressBarMetadata = ComponentMetadata.make({
  name: "ProgressBar",
  title: "进度条",
  slug: "progress-bar",
  catalog: "standalone",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生 progressbar 值语义与外层 Model",
  status: "verified",
  family: "feedback",
  dependencies: ["@heroui/styles/components/progress-bar", "foldkit/html"],
  anatomy: ["progressbar root", "optional label", "optional output", "track", "fill"],
  publicParts: ["view", "Value"],
  states: ["determinate", "indeterminate", "color", "size"],
  slots: ["label", "output", "track", "fill"],
  heroUi: { version: "3.2.4", module: "progress-bar" },
  foldkit: { primitive: "原生 role=progressbar 与 aria-valuemin/max/now/text" },
  examples: ["controlled", "indeterminate", "colors", "sizes", "custom-output"],
  differences: ["不移植 React Aria ProgressBar；值与更新 Message 完全由外层 Model 持有。"],
});

export const progressCircleMetadata = ComponentMetadata.make({
  name: "ProgressCircle",
  title: "环形进度",
  slug: "progress-circle",
  catalog: "standalone",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生 progressbar 值语义与外层 Model",
  status: "verified",
  family: "feedback",
  dependencies: ["@heroui/styles/components/progress-circle", "foldkit/html"],
  anatomy: ["progressbar root", "svg track", "track circle", "fill circle"],
  publicParts: ["view", "Value"],
  states: ["determinate", "indeterminate", "color", "size"],
  slots: ["track", "track-circle", "fill-circle"],
  heroUi: { version: "3.2.4", module: "progress-circle" },
  foldkit: { primitive: "原生 role=progressbar 与 aria-valuemin/max/now/text" },
  examples: ["controlled", "indeterminate", "colors", "sizes", "custom-label"],
  differences: ["与 ProgressBar 共用值契约，不移植 React Context；SVG 仅改变 visual anatomy。"],
});

export const meterMetadata = ComponentMetadata.make({
  name: "Meter",
  title: "计量器",
  slug: "meter",
  catalog: "standalone",
  phase: 1,
  behaviorClass: "A",
  behaviorAuthority: "原生 meter 值语义与调用方阈值事实",
  status: "verified",
  family: "data-display",
  dependencies: ["@heroui/styles/components/meter", "foldkit/html"],
  anatomy: ["meter root", "optional label", "optional output", "track", "fill"],
  publicParts: ["view"],
  states: ["range", "default", "accent", "success", "warning", "danger", "size"],
  slots: ["label", "output", "track", "fill"],
  heroUi: { version: "3.2.4", module: "meter" },
  foldkit: { primitive: "原生 role=meter 与 aria-valuemin/max/now/text" },
  examples: ["range", "boundary-colors", "sizes", "custom-output", "long-label"],
  differences: ["不从数值推断阈值颜色；调用方拥有边界规则并显式选择 color。"],
});

export const avatarMetadata = ComponentMetadata.make({
  name: "Avatar",
  title: "头像",
  slug: "avatar",
  catalog: "standalone",
  phase: 1,
  behaviorClass: "B",
  behaviorAuthority: "外层 Model 与 Foldkit 原生 img load/error 事件",
  status: "verified",
  family: "data-display",
  dependencies: ["@heroui/styles/components/avatar", "foldkit/html"],
  anatomy: ["avatar root", "fallback", "optional image"],
  publicParts: ["view", "ImageStatus", "ImageState"],
  states: ["loading", "loaded", "failed", "missing", "color", "size", "variant"],
  slots: ["avatar", "avatar-fallback", "avatar-image"],
  heroUi: { version: "3.2.4", module: "avatar" },
  foldkit: { primitive: "原生 img、OnLoad 与 OnError" },
  examples: ["controlled", "loaded", "failed", "missing", "colors-sizes", "soft", "custom"],
  differences: [
    "不移植 React 的 useImageProps；调用方 Model 消费 Foldkit img 事件并传回 ImageState。",
  ],
});

export const scrollShadowMetadata = ComponentMetadata.make({
  name: "ScrollShadow",
  title: "滚动阴影",
  slug: "scroll-shadow",
  catalog: "parts",
  phase: 1,
  behaviorClass: "B",
  behaviorAuthority: "Foldkit Mount、原生 scroll、ResizeObserver 与 MutationObserver",
  status: "verified",
  family: "layout",
  dependencies: ["@heroui/styles/components/scroll-shadow", "foldkit/mount"],
  anatomy: ["scroll container", "scroll-shadow slot", "内容"],
  publicParts: ["view", "ObserveScrollShadow", "Visibility", "Orientation"],
  states: ["none", "start", "end", "both", "vertical", "horizontal", "fade"],
  slots: ["scroll-shadow"],
  heroUi: { version: "3.2.4", module: "scroll-shadow" },
  foldkit: { primitive: "Mount.defineStream、原生 scroll 与 DOM observers" },
  examples: ["vertical", "horizontal", "overflow", "no-overflow", "controlled"],
  differences: ["不移植 React hook；Mount 生命周期观察 DOM，外层 Model 持有可见边缘。"],
});

export const buttonMetadata = ComponentMetadata.make({
  name: "Button",
  title: "按钮",
  slug: "button",
  catalog: "standalone",
  phase: 2,
  behaviorClass: "B",
  behaviorAuthority: "Foldkit Button 的 click、disabled、keyboard 与 aria-disabled 契约",
  status: "verified",
  family: "actions",
  dependencies: ["@heroui/styles/components/button", "@foldkit/ui/button"],
  anatomy: ["native button", "optional leading/trailing content", "optional pending indicator"],
  publicParts: ["view"],
  states: ["variant", "size", "icon-only", "pending", "disabled", "full-width"],
  slots: ["button", "leading", "trailing", "spinner"],
  heroUi: { version: "3.2.4", module: "button" },
  foldkit: { primitive: "@foldkit/ui/button" },
  examples: ["default", "sizes", "icon-only", "full-width", "pending", "disabled"],
  differences: ["pending 映射为 Foldkit Button 的 disabled 事实，不创建独立加载状态机。"],
});

export const buttonGroupMetadata = ComponentMetadata.make({
  name: "ButtonGroup",
  title: "按钮组",
  slug: "button-group",
  catalog: "parts",
  phase: 2,
  behaviorClass: "A",
  behaviorAuthority: "成员 Button 各自拥有 Message、disabled 与焦点行为",
  status: "verified",
  family: "actions",
  dependencies: ["@heroui/styles/components/button-group", "foldkit/html"],
  anatomy: ["button-group root", "direct Button children", "decorative separators"],
  publicParts: ["view", "separatorView"],
  states: ["horizontal", "vertical", "full-width", "compact", "overflow"],
  slots: ["button-group", "button-group-separator"],
  heroUi: { version: "3.2.4", module: "button-group" },
  foldkit: { primitive: "成员原生 Button 与调用方 Message" },
  examples: ["horizontal", "vertical", "compact", "full-width", "overflow", "controlled"],
  differences: ["不移植 React Context 或 Group；wrapper 不转发或拦截成员状态与事件。"],
});

export const closeButtonMetadata = ComponentMetadata.make({
  name: "CloseButton",
  title: "关闭按钮",
  slug: "close-button",
  catalog: "standalone",
  phase: 2,
  behaviorClass: "B",
  behaviorAuthority: "Foldkit Button 的 click、disabled、keyboard 与 aria-disabled 契约",
  status: "verified",
  family: "actions",
  dependencies: ["@heroui/styles/components/close-button", "@foldkit/ui/button"],
  anatomy: ["native button", "decorative close icon"],
  publicParts: ["view"],
  states: ["default", "disabled", "focus"],
  slots: ["close-button", "close-button-icon"],
  heroUi: { version: "3.2.4", module: "close-button" },
  foldkit: { primitive: "@foldkit/ui/button" },
  examples: ["default", "custom-label", "disabled"],
  differences: ["组件要求调用方提供 accessibleLabel，父级拥有是否关闭的状态。"],
});

export const linkMetadata = ComponentMetadata.make({
  name: "Link",
  title: "链接",
  slug: "link",
  catalog: "standalone",
  phase: 2,
  behaviorClass: "B",
  behaviorAuthority: "原生 anchor 的导航、键盘、焦点与浏览器访问状态",
  status: "verified",
  family: "actions",
  dependencies: ["@heroui/styles/components/link", "foldkit/html"],
  anatomy: ["native anchor", "optional external icon"],
  publicParts: ["view"],
  states: ["default", "current", "external", "disabled", "focus", "visited"],
  slots: ["link", "link-icon", "link-default-icon"],
  heroUi: { version: "3.2.4", module: "link" },
  foldkit: { primitive: "原生 a、href 与调用方 Message" },
  examples: ["default", "controlled", "current", "external", "disabled", "button-boundary"],
  differences: [
    "disabled Link 不带 href 或 click Message，因此不伪造可用导航。visited 由浏览器隐私模型管理，组件不读取或覆盖。",
  ],
});

export const metadata: ReadonlyArray<ComponentMetadata> = [
  typographyMetadata,
  surfaceMetadata,
  separatorMetadata,
  labelMetadata,
  descriptionMetadata,
  headerMetadata,
  errorMessageMetadata,
  fieldErrorMetadata,
  kbdMetadata,
  badgeMetadata,
  chipMetadata,
  cardMetadata,
  skeletonMetadata,
  emptyStateMetadata,
  alertMetadata,
  spinnerMetadata,
  progressBarMetadata,
  progressCircleMetadata,
  meterMetadata,
  avatarMetadata,
  scrollShadowMetadata,
  buttonMetadata,
  buttonGroupMetadata,
  closeButtonMetadata,
  linkMetadata,
];
